#ifndef MANGODATABASE_GLOBAL_H
#define MANGODATABASE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MANGODATABASE_LIBRARY)
#  define MANGODATABASESHARED_EXPORT Q_DECL_EXPORT
#else
#  define MANGODATABASESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MANGODATABASE_GLOBAL_H
