#ifndef MANGOSERVICE_GLOBAL_H
#define MANGOSERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MANGOSERVICE_LIBRARY)
#  define MANGOSERVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define MANGOSERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MANGOSERVICE_GLOBAL_H
